begin;

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  actor_user_id uuid null,
  actor_role text null,
  table_schema text not null,
  table_name text not null,
  operation text not null check (operation in ('INSERT', 'UPDATE', 'DELETE')),
  row_id text null,
  changed_columns text[] null,
  old_row jsonb null,
  new_row jsonb null,
  ip_address inet null,
  user_agent text null,
  transaction_id bigint not null default txid_current()
);

create index if not exists audit_logs_created_at_idx on public.audit_logs (created_at desc);
create index if not exists audit_logs_table_name_idx on public.audit_logs (table_name);
create index if not exists audit_logs_actor_user_id_idx on public.audit_logs (actor_user_id);
create index if not exists audit_logs_operation_idx on public.audit_logs (operation);

alter table public.audit_logs enable row level security;

revoke all on table public.audit_logs from anon, authenticated;
grant select on table public.audit_logs to authenticated;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(
    (
      select p.role = 'admin'
      from public.profiles p
      where p.id = auth.uid()
    ),
    false
  );
$$;

revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to authenticated;

drop policy if exists audit_logs_select_admin on public.audit_logs;
create policy audit_logs_select_admin
on public.audit_logs
for select
to authenticated
using (public.is_admin());

create or replace function public.log_audit_event()
returns trigger
language plpgsql
security definer
set search_path = public, pg_catalog
as $$
declare
  v_actor_user_id uuid;
  v_claims jsonb;
  v_headers jsonb;
  v_actor_role text;
  v_row_id text;
  v_changed_columns text[];
  v_ip inet;
  v_user_agent text;
begin
  if tg_table_schema = 'public' and tg_table_name = 'audit_logs' then
    return coalesce(new, old);
  end if;

  v_actor_user_id := auth.uid();

  begin
    if current_setting('request.jwt.claims', true) is not null
       and current_setting('request.jwt.claims', true) <> '' then
      v_claims := current_setting('request.jwt.claims', true)::jsonb;
    end if;
  exception when others then
    v_claims := null;
  end;

  begin
    if current_setting('request.headers', true) is not null
       and current_setting('request.headers', true) <> '' then
      v_headers := current_setting('request.headers', true)::jsonb;
    end if;
  exception when others then
    v_headers := null;
  end;

  v_actor_role := coalesce(v_claims ->> 'role', auth.role());
  v_ip := inet_client_addr();
  v_user_agent := coalesce(v_headers ->> 'user-agent', v_headers ->> 'x-client-info');

  if tg_op = 'INSERT' then
    v_row_id := to_jsonb(new) ->> 'id';

    insert into public.audit_logs (
      actor_user_id,
      actor_role,
      table_schema,
      table_name,
      operation,
      row_id,
      new_row,
      ip_address,
      user_agent
    )
    values (
      v_actor_user_id,
      v_actor_role,
      tg_table_schema,
      tg_table_name,
      tg_op,
      v_row_id,
      to_jsonb(new),
      v_ip,
      v_user_agent
    );

    return new;
  end if;

  if tg_op = 'UPDATE' then
    if to_jsonb(old) = to_jsonb(new) then
      return new;
    end if;

    v_row_id := coalesce(to_jsonb(new) ->> 'id', to_jsonb(old) ->> 'id');

    select coalesce(array_agg(n.key order by n.key), '{}')
      into v_changed_columns
    from jsonb_each(to_jsonb(new)) n
    left join jsonb_each(to_jsonb(old)) o on o.key = n.key
    where n.value is distinct from o.value;

    insert into public.audit_logs (
      actor_user_id,
      actor_role,
      table_schema,
      table_name,
      operation,
      row_id,
      changed_columns,
      old_row,
      new_row,
      ip_address,
      user_agent
    )
    values (
      v_actor_user_id,
      v_actor_role,
      tg_table_schema,
      tg_table_name,
      tg_op,
      v_row_id,
      v_changed_columns,
      to_jsonb(old),
      to_jsonb(new),
      v_ip,
      v_user_agent
    );

    return new;
  end if;

  if tg_op = 'DELETE' then
    v_row_id := to_jsonb(old) ->> 'id';

    insert into public.audit_logs (
      actor_user_id,
      actor_role,
      table_schema,
      table_name,
      operation,
      row_id,
      old_row,
      ip_address,
      user_agent
    )
    values (
      v_actor_user_id,
      v_actor_role,
      tg_table_schema,
      tg_table_name,
      tg_op,
      v_row_id,
      to_jsonb(old),
      v_ip,
      v_user_agent
    );

    return old;
  end if;

  return coalesce(new, old);
end;
$$;

do $$
declare
  t record;
begin
  for t in
    select tablename
    from pg_tables
    where schemaname = 'public'
      and tablename in ('profiles', 'contacts', 'loans', 'payments', 'p2p_requests', 'payment_history')
  loop
    execute format('drop trigger if exists trg_audit_%I on public.%I', t.tablename, t.tablename);
    execute format(
      'create trigger trg_audit_%I after insert or update or delete on public.%I for each row execute function public.log_audit_event()',
      t.tablename,
      t.tablename
    );
  end loop;
end
$$;

commit;;
